services:
  - type: web
    name: kams-ground-shipping
    runtime: python
    plan: free
    buildCommand: cd shipping_project-main && pip install -r requirements.txt
    startCommand: cd shipping_project-main && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
